KnockoutMVC/Models/DbContext.cs
using System.Data.Entity;

namespace KnockoutMVC.Models
{
    public partial class DbContext : System.Data.Entity.DbContext
    {
        public DbContext()
            : base("name=DbContext")
        {
        }

        public virtual DbSet<MTB_Articles> MTB_Articles { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }
    }
}

KnockoutMVC/Models/MTB_Articles.cs
using System.ComponentModel.DataAnnotations;

namespace KnockoutMVC.Models
{
    public partial class MTB_Articles
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }

        [Required]
        [StringLength(100)]
        public string Excerpts { get; set; }

        [Required]
        [StringLength(1000)]
        public string Content { get; set; }
    }
}

KnockoutMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KnockoutMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

KnockoutMVC/Controllers/MTB_ArticlesController.cs
using KnockoutMVC.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace KnockoutMVC.Controllers
{
    public class MTB_ArticlesController : Controller
    {
        private Models.DbContext db = new Models.DbContext();

        // GET: MTB_Articles
        public ActionResult Index()
        {
            return View(db.MTB_Articles.ToList());
        }

        // GET: MTB_Articles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MTB_Articles mTB_Articles = db.MTB_Articles.Find(id);
            if (mTB_Articles == null)
            {
                return HttpNotFound();
            }
            return View(mTB_Articles);
        }

        // GET: MTB_Articles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MTB_Articles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Excerpts,Content")] MTB_Articles mTB_Articles)
        {
            if (ModelState.IsValid)
            {
                db.MTB_Articles.Add(mTB_Articles);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mTB_Articles);
        }

        public ActionResult CreateJS()
        {
            return View();
        }
        [HttpPost]
        public JsonResult CreateJS(MTB_Articles mtb_article)
        {
            if (ModelState.IsValid)
            {
                db.MTB_Articles.Add(mtb_article);
                db.SaveChanges();
              
            }
            return Json(mtb_article,JsonRequestBehavior.AllowGet);
        }



        // GET: MTB_Articles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MTB_Articles mTB_Articles = db.MTB_Articles.Find(id);
            if (mTB_Articles == null)
            {
                return HttpNotFound();
            }
            return View(mTB_Articles);
        }

        // POST: MTB_Articles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Excerpts,Content")] MTB_Articles mTB_Articles)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mTB_Articles).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mTB_Articles);
        }

        // GET: MTB_Articles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MTB_Articles mTB_Articles = db.MTB_Articles.Find(id);
            if (mTB_Articles == null)
            {
                return HttpNotFound();
            }
            return View(mTB_Articles);
        }

        // POST: MTB_Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MTB_Articles mTB_Articles = db.MTB_Articles.Find(id);
            db.MTB_Articles.Remove(mTB_Articles);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public JsonResult FillIndex()
        {
            return Json(db.MTB_Articles.ToList(), JsonRequestBehavior.AllowGet);
        }
    }
}

KnockoutMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

KnockoutMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

KnockoutMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

KnockoutMVC/Views/MTB_Articles/Create.cshtml
@model KnockoutMVC.Models.MTB_Articles

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


<!--@*@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MTB_Articles</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Excerpts, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Excerpts, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Excerpts, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}*@ 

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

    -->
<div class="span12">
 
        <legend>Create Articles</legend>
        <div class="control-group">
            <label class="control-label">Title: </label>
            <div class="controls">
                <input type="text" data-bind="value: Title" placeholder="Article Title" class="input-medium">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Excerpts: </label>
            <div class="controls">
                <textarea data-bind="value: Excerpts" placeholder="Article Excerpts" rows="3"></textarea>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Content: </label>
            <div class="controls">
                <textarea data-bind="value: Content" placeholder="Article Content" rows="6" class="input-xxlarge"></textarea>
            </div>
        </div>
        <div class="control-group">
            <input type="button" value="Save" data-bind="click: btnCreateArticle" class="btn btn-primary" />
            <a href="@Url.Action("", "MTB_Articles")" class="btn btn-primary">Cancel</a>
        </div>
 
</div>


@section Scripts {
 @*@Scripts.Render("~/bundles/jqueryval")*@  
<script src="~/Scripts/app/CreateVM.js"></script>
}

KnockoutMVC/Views/MTB_Articles/Delete.cshtml
@model KnockoutMVC.Models.MTB_Articles

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MTB_Articles</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Excerpts)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Excerpts)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>
 

KnockoutMVC/Views/MTB_Articles/Details.cshtml
@model KnockoutMVC.Models.MTB_Articles

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MTB_Articles</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Excerpts)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Excerpts)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KnockoutMVC/Views/MTB_Articles/Edit.cshtml
@model KnockoutMVC.Models.MTB_Articles

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MTB_Articles</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Excerpts, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Excerpts, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Excerpts, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KnockoutMVC/Views/MTB_Articles/Index.cshtml
@model IEnumerable<KnockoutMVC.Models.MTB_Articles>

@{
    ViewBag.Title = "Index";
}

<!--<h2>Index</h2>

<p>
 <a class="btn btn-primary" href="@Url.Action("Create","MTB_Articles")">Create New</a>   
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Excerpts)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Excerpts)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Content)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>-->
 
<h2>Articles</h2>
<p>
    <a href="@Url.Action("Create", "MTB_Articles")" class="btn btn-primary btn-large">Create New »</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Excerpts</th>
            <th>Content</th>
        </tr>
    </thead>
    <tbody data-bind="foreach: Articles">
        <tr>
            <td data-bind="text: Title"></td>
            <td data-bind="text: Excerpts"></td>
            <td data-bind="text: Content"></td>
        </tr>
    </tbody>
</table>
@section Scripts {
    @*@Scripts.Render("~/Scripts/ViewModel/IndexVM.js")*@
    <script src="~/Scripts/app/IndexVM.js"></script>
}

KnockoutMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/knockoutjs")
    @RenderSection("scripts", required: false)
</body>
</html>